spring.application.name=runtime-agent
server.port=9000

runtime-agent.api-token=change-me
runtime-agent.docker-command=docker
runtime-agent.managed-network=tipi_main_network
runtime-agent.local-apps-path=/workspace/appstore/apps
runtime-agent.local-data-path=/workspace/data/apps
runtime-agent.local-domain=localhost
